/************No.1: R001******************HD_ZBMX_HZ***R001******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R001')
begin
	print '新增指标R001,但指标R001已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R001') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R001','停诊次数','select "R001" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select timekey,yykey,kskey,sum(1)  fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.tzbz = 1 group by timekey,yykey,kskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R001" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,sum(1)  fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.tzbz = 1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R001" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,sum(1)  fz from FACT_RLZY_QJFX a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) and a.tzbz = 1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1")','1','','','13215','','','0','1','-1','FACT_RLZY_QJFX','sum(1)  fz','where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.tzbz = 1','timekey,yykey,kskey','','select "R001" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,sum(1)  fz from FACT_RLZY_QJFX a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) and a.tzbz = 1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1")','','1')
	
end
go

/************No.2: R0010******************HD_ZBMX_HZ***R0010******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R0010')
begin
	print '新增指标R0010,但指标R0010已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R0010') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R0010','平均接诊量','','select timekey,yykey,kskey,yskey,sum(ghrc) fz,0 fm from FACT_YY_MZ_JZRC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey,yskey union all select timekey,yykey,kskey,yskey,0 fz,sum(sfcz) fm from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey,yskey','','select ''R0010'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R009'' and month between @kssj and @jssj union all select yykey,yydm,kskey,ksdm,month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R007'' and month between @kssj and @jssj)t group by yykey,yydm,kskey,ksdm,month,bqkey','select ''R0010'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R009'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R007'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','1','','R009,R007','12514','','','0','-1','-1','','','','timekey,yykey,kskey,yskey','接诊量(R009)/@出诊次数(R007)','select ''R0010'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R009'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R007'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','','0')
	
end
go

/************No.3: R0011******************HD_ZBMX_HZ***R0011******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R0011')
begin
	print '新增指标R0011,但指标R0011已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R0011') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R0011','开诊时长','select ''R0011'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select yykey,kskey,timekey,yskey,sum(kaizsc) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R0011'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(kaizsc) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R0011'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(kaizsc) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'')','1','','','0','','','0','1','0','FACT_YY_MZ_YSCQ','kaizsc','','yykey,kskey,timekey,yskey','','select ''R0011'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(kaizsc) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'')','','0')
	
end
go

/************No.4: R0012******************HD_ZBMX_HZ***R0012******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R0012')
begin
	print '新增指标R0012,但指标R0012已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R0012') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R0012','平均开诊时长','','select yykey,kskey,timekey,yskey,sum(kaizsc) fz,0 fm from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey union all select yykey,kskey,timekey,yskey,0 fz,sum(sfcz) fm from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey','','select ''R0012'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R0011'' and month between @kssj and @jssj union all select yykey,yydm,kskey,ksdm,month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R007'' and month between @kssj and @jssj)t group by yykey,yydm,kskey,ksdm,month,bqkey','select ''R0012'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R0011'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R007'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','1','','R0011,R007','12515','','','0','-1','-1','','','','yykey,kskey,timekey,yskey','@开诊时长(R0011)/@出诊次数(R007)','select ''R0012'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R0011'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R007'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','','0')
	
end
go

/************No.5: R0013******************HD_ZBMX_HZ***R0013******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R0013')
begin
	print '新增指标R0013,但指标R0013已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R0013') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R0013','看诊时长','select ''R0013'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select yykey,kskey,timekey,yskey,sum(kanzsc) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R0013'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(kanzsc) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R0013'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(kanzsc) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'')','1','','','0','','','0','1','0','FACT_YY_MZ_YSCQ','kanzsc','','yykey,kskey,timekey,yskey','','select ''R0013'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(kanzsc) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'')','','0')
	
end
go

/************No.6: R0014******************HD_ZBMX_HZ***R0014******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R0014')
begin
	print '新增指标R0014,但指标R0014已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R0014') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R0014','平均看诊时长','','select yykey,kskey,timekey,yskey,sum(kanzsc) fz,0 fm from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey union all select yykey,kskey,timekey,yskey,0 fz,sum(ghrc) fm from FACT_YY_MZ_JZRC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey','','select ''R0014'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R0013'' and month between @kssj and @jssj union all select yykey,yydm,kskey,ksdm,month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R009'' and month between @kssj and @jssj)t group by yykey,yydm,kskey,ksdm,month,bqkey','select ''R0014'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R0013'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R009'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','1','','R0013,R009','12516','','','0','-1','-1','','','','yykey,kskey,timekey,yskey','@看诊时长(R0013)/@接诊量(R009)','select ''R0014'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R0013'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R009'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','','0')
	
end
go

/************No.7: R0015******************HD_ZBMX_HZ***R0015******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R0015')
begin
	print '新增指标R0015,但指标R0015已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R0015') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R0015','候诊时长','select ''R0015'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select yykey,kskey,timekey,yskey,sum(houzsc) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R0015'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(houzsc) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R0015'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(houzsc) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'')','1','','','0','','','0','1','0','FACT_YY_MZ_YSCQ','houzsc','','yykey,kskey,timekey,yskey','','select ''R0015'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(houzsc) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'')','','0')
	
end
go

/************No.8: R0016******************HD_ZBMX_HZ***R0016******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R0016')
begin
	print '新增指标R0016,但指标R0016已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R0016') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R0016','平均候诊时长','','select yykey,kskey,timekey,yskey,sum(houzsc) fz,0 fm from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey union all select yykey,kskey,timekey,yskey,0 fz,sum(ghrc) fm from FACT_YY_MZ_JZRC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey','','select ''R0016'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R0015'' and month between @kssj and @jssj union all select yykey,yydm,kskey,ksdm,month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id =''R009'' and month between @kssj and @jssj)t group by yykey,yydm,kskey,ksdm,month,bqkey','select ''R0016'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R0015'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id =''R009'' and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','1','','R0015,R009','12517','','','0','-1','-1','','','','yykey,kskey,timekey,yskey','@候诊时长(R0015)/@接诊量(R009)','select ''R0016'' zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R0015'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id =''R009'' and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','','0')
	
end
go

/************No.9: R002******************HD_ZBMX_HZ***R002******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R002')
begin
	print '新增指标R002,但指标R002已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R002') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R002','医生班次','select "R002" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select yykey,kskey,timekey,sum(pbyss) fz from FACT_YY_MZ_KSYSBC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R002" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,sum(pbyss) fz from FACT_YY_MZ_KSYSBC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R002" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,sum(pbyss) fz from FACT_YY_MZ_KSYSBC a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1")','1','','','13216','','','0','1','0','FACT_YY_MZ_KSYSBC','pbyss','','yykey,kskey,timekey','','select "R002" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,sum(pbyss) fz from FACT_YY_MZ_KSYSBC a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1")','','')
	
end
go

/************No.10: R003******************HD_ZBMX_HZ***R003******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R003')
begin
	print '新增指标R003,但指标R003已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R003') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R003','停诊率','','select timekey,yykey,kskey,sum(1) fz,0 fm from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.tzbz = 1 group by timekey,yykey,kskey union all select timekey,yykey,kskey,0 fz,sum(pbyss) fm from FACT_YY_MZ_KSYSBC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey','','select "R003" zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id ="R001" and month between @kssj and @jssj union all select yykey,yydm,kskey,ksdm,month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id ="R002" and month between @kssj and @jssj)t group by yykey,yydm,kskey,ksdm,month,bqkey','select "R003" zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id ="R001" and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id ="R002" and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','1','','R001,R002','12511','','','0','-1','-1','','','','timekey,yykey,kskey','@停诊次数(R001)/@医生班次(R002)','select "R003" zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id ="R001" and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id ="R002" and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','','')
	
end
go

/************No.11: R004******************HD_ZBMX_HZ***R004******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R004')
begin
	print '新增指标R004,但指标R004已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R004') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R004','请假天数','select "R004" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select yykey,timekey,kskey,yskey,zyjszgkey,sum(qjsc) fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,timekey,kskey,yskey,zyjszgkey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R004" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,timekey,kskey,yskey,zyjszgkey,sum(qjsc) fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,timekey,kskey,yskey,zyjszgkey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R004" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,timekey,kskey,yskey,zyjszgkey,sum(qjsc) fz from FACT_RLZY_QJFX a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,timekey,kskey,yskey,zyjszgkey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1")','1','','','','','','0','1','0','FACT_RLZY_QJFX','qjsc','','yykey,timekey,kskey,yskey,zyjszgkey','','select "R004" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,timekey,kskey,yskey,zyjszgkey,sum(qjsc) fz from FACT_RLZY_QJFX a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,timekey,kskey,yskey,zyjszgkey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1")','','')
	
end
go

/************No.12: R005******************HD_ZBMX_HZ***R005******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R005')
begin
	print '新增指标R005,但指标R005已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R005') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R005','按时出诊次数','select "R005" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select timekey,yykey,kskey,sum(1) fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.cdbz<>1 group by timekey,yykey,kskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R005" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,sum(1) fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.cdbz<>1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R005" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,sum(1) fz from FACT_RLZY_QJFX a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) and a.cdbz<>1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1")','1','','','13217','','','0','1','-1','FACT_RLZY_QJFX','sum(1) fz','where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.cdbz<>1','timekey,yykey,kskey','','select "R005" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,sum(1) fz from FACT_RLZY_QJFX a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) and a.cdbz<>1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1")','','1')
	
end
go

/************No.13: R006******************HD_ZBMX_HZ***R006******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R006')
begin
	print '新增指标R006,但指标R006已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R006') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R006','按时出诊率','','select timekey,yykey,kskey,sum(1) fz,0 fm from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and a.cdbz<>1 group by timekey,yykey,kskey union all select timekey,yykey,kskey,0 fz,sum(sfcz) fm from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey','','select "R006" zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id ="R005" and month between @kssj and @jssj union all select yykey,yydm,kskey,ksdm,month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where zbmx_id ="R007" and month between @kssj and @jssj)t group by yykey,yydm,kskey,ksdm,month,bqkey','select "R006" zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id ="R005" and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(year,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(year,1,month) < getdate() and zbmx_id ="R007" and month between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','1','','R005,R007','12513','','','0','-1','-1','','','','timekey,yykey,kskey','@按时出诊次数(R005)/@出诊次数(R007)','select "R006" zbmx_id,yykey,yydm,kskey,ksdm,month,sum(fz) fz,sum(fm) fm,null czry,getdate() gxrq,bqkey from (select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,fz,0 fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id ="R005" and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) union all select yykey,yydm,kskey,ksdm,dateadd(month,1,month) month,0 fz,fz fm,bqkey from FACT_RESULT_KS_VALUE_M where dateadd(month,1,month) < getdate() and zbmx_id ="R007" and month between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj))t group by yykey,yydm,kskey,ksdm,month,bqkey','','')
	
end
go

/************No.14: R007******************HD_ZBMX_HZ***R007******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R007')
begin
	print '新增指标R007,但指标R007已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R007') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R007','出诊次数','select ''R007'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select yykey,kskey,timekey,yskey,sum(sfcz) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R007'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(sfcz) fz from FACT_YY_MZ_YSCQ a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R007'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(sfcz) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'')','1','','','0','','','0','1','0','FACT_YY_MZ_YSCQ','sfcz','','yykey,kskey,timekey,yskey','','select ''R007'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select yykey,kskey,timekey,yskey,sum(sfcz) fz from FACT_YY_MZ_YSCQ a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by yykey,kskey,timekey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'')','','0')
	
end
go

/************No.15: R008******************HD_ZBMX_HZ***R008******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R008')
begin
	print '新增指标R008,但指标R008已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R008') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R008','脱岗次数','select "R008" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select timekey,yykey,kskey,count(1) fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and tgbz=1 group by timekey,yykey,kskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R008" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,count(1) fz from FACT_RLZY_QJFX a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and tgbz=1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+"1")','select "R008" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,count(1) fz from FACT_RLZY_QJFX a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) and tgbz=1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+"1")','1','','','','','','0','1','-1','FACT_RLZY_QJFX','count(1) fz','where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) and tgbz=1','timekey,yykey,kskey','','select "R008" zbmx_id,a.yykey,isnull(b.yydm,"01") yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1") month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,count(1) fz from FACT_RLZY_QJFX a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) and tgbz=1 group by timekey,yykey,kskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+"1")','','1')
	
end
go

/************No.16: R009******************HD_ZBMX_HZ***R009******************************/

if exists(select 1 from HD_ZBMX_HZ where zb_id='R009')
begin
	print '新增指标R009,但指标R009已存在于表HD_ZBMX_HZ中,请核查!'
end
if not exists(select 1 from HD_ZBMX_HZ where zb_id='R009') 
begin 
	INSERT HD_ZBMX_HZ ( zb_id,zb_name,sql_start,sql_middle,sql_end,sql_text,tqsql_text,jlzt,memo,dependindex,orderno,sql_text_first,proc_name,zbzt,ysfs,kslx,fact_table,fact_dlz,condition,kxwdz,gspz,hqsql_text,dlzgs,dylx)
	values('R009','接诊量','select ''R009'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (','select timekey,yykey,kskey,yskey,sum(ghrc) fz from FACT_YY_MZ_JZRC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey,yskey',') a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R009'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,yskey,sum(ghrc) fz from FACT_YY_MZ_JZRC a where timekey between @kssj and @jssj and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),timekey,120)+''1'')','select ''R009'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,yskey,sum(ghrc) fz from FACT_YY_MZ_JZRC a where timekey between dateadd(year,-1,@kssj) and dateadd(year,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(year,1,timekey),120)+''1'')','1','','','0','','','0','1','0','FACT_YY_MZ_JZRC','ghrc','','timekey,yykey,kskey,yskey','','select ''R009'' zbmx_id,a.yykey,isnull(b.yydm,''01'') yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'') month,sum(fz) fz,0 fm,null czry,getdate() gxrq,null bqkey from (select timekey,yykey,kskey,yskey,sum(ghrc) fz from FACT_YY_MZ_JZRC a where timekey between dateadd(month,-1,@kssj) and dateadd(month,-1,@jssj) and (a.yykey in (@yykey) or -1 in (@yykey)) group by timekey,yykey,kskey,yskey) a inner join DIM_YYXX b on a.yykey=b.yykey inner join DIM_KSXX c on a.kskey=c.kskey and a.yykey=c.yykey group by a.yykey,b.yydm,a.kskey,c.ksdm,convert(date,convert(char(8),dateadd(month,1,timekey),120)+''1'')','','0')
	
end
go

